
# services:
#   app:
#     build: .
#     ports:
#       - "8080:8080"
#     depends_on:
#       - redis
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6379

#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6380:6379"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./transformer.pdf:/app/data/transformer.pdf
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
